### ISSUE TITLE
URL to wiki and repository

### ISSUE THREAD

**Issue by catalinarp** [maasha/biopieces#4]
Good afternoon!
I have been trying to use the script biopieces_installer-0.53.sh to install the tools and it is not able to find the new URLs for the repository and the wiki in the last few steps: 
svn: E170000: URL 'https://github.com/maasha/biopieces/wiki' doesn't exist
FAIL
abort
I already modified the script to add the new repository URL (https://github.com/maasha/biopieces.git) but it hasn't worked with the wiki. Is there something else I should do? Thanks!

**Comment by maasha** [comment]
The biopieces installer is obsolete. You should follow the Installation instructions:

https://github.com/maasha/biopieces/wiki/Installation
